{
	"version": 1527276526,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/logo-sheet0.png",
		"images/fundoabertura-sheet0.png",
		"images/play-sheet0.png",
		"images/nomejogo-sheet0.png",
		"images/personagem-sheet0.png",
		"images/cénario.png",
		"images/returne-sheet0.png",
		"images/returne-sheet1.png",
		"images/mae-sheet0.png",
		"images/mae-sheet1.png",
		"images/obstaculo1-sheet0.png",
		"images/obtaculo2-sheet0.png",
		"images/obstaculo3-sheet0.png",
		"images/vida_maxima-sheet0.png",
		"images/newgame-sheet0.png",
		"images/creditos-sheet0.png",
		"images/vida-sheet0.png",
		"images/sensorcriaritem-sheet0.png",
		"images/music-sheet0.png",
		"images/music-sheet1.png",
		"images/music-sheet2.png",
		"images/hist-sheet0.png",
		"images/tobecontinued-sheet0.png",
		"images/eloisa-sheet0.png",
		"images/maciel-sheet0.png",
		"images/pedro-sheet0.png",
		"images/chao.png",
		"images/cenario-sheet0.png",
		"images/cenario-sheet1.png",
		"images/gameover-sheet0.png",
		"images/spritefont.png",
		"images/descrição-sheet0.png",
		"images/fundo-sheet0.png",
		"images/vidaextra-sheet0.png",
		"images/candy-sheet0.png",
		"images/botaomenu-sheet0.png",
		"images/astesgameover-sheet0.png",
		"images/obstaculopassaro-sheet0.png",
		"images/objetochinela-sheet0.png",
		"media/botoes.m4a",
		"media/botoes.ogg",
		"media/pulo ou lupin.m4a",
		"media/pulo ou lupin.ogg",
		"media/coletaa.m4a",
		"media/coletaa.ogg",
		"media/tema.m4a",
		"media/tema.ogg",
		"media/menu (online-audio-converter.com).m4a",
		"media/menu (online-audio-converter.com).ogg",
		"media/explosão.m4a",
		"media/explosão.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/musica história.m4a",
		"media/musica história.ogg",
		"media/vidro.m4a",
		"media/vidro.ogg",
		"media/efeito sonoro jogo 1.m4a",
		"media/efeito sonoro jogo 1.ogg",
		"media/trilha sonora do credito.m4a",
		"media/trilha sonora do credito.ogg",
		"media/musica para o game over.m4a",
		"media/musica para o game over.ogg",
		"media/colisão com objeto.m4a",
		"media/colisão com objeto.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}