{
	"version": 1527094248,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/logogame-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/botãoplay-sheet0.png",
		"images/newgame.png",
		"images/ideck-sheet0.png",
		"images/icard-sheet0.png",
		"images/icard-sheet1.png",
		"images/senscard-sheet0.png",
		"images/bmenu-sheet0.png",
		"images/bsound-sheet0.png",
		"images/bsound-sheet1.png",
		"images/bmusic-sheet0.png",
		"images/bmusic-sheet1.png",
		"images/ipointe-sheet0.png",
		"media/iwan gabovitch - dark ambience loop.ogg",
		"media/draw.m4a",
		"media/draw.ogg",
		"media/passturn.m4a",
		"media/passturn.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/untap.m4a",
		"media/untap.ogg",
		"media/path to lake land.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}